=== dandoh/intellij-dtlc/lang/schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"properties": {
		"languageName": {
			"type": "string"
		},
		"constantPrefix": {
			"type": "string"
		},
		"exeName": {
			"type": "string"
		},
		"runConfigInit": {
			"type": "string"
		},
		"trimVersion": {
			"type": "string"
		},
		"supportsParsing": {
			"type": "boolean"
		},
		"generateCliState": {
			"type": "boolean"
		},
		"hasVersion": {
			"type": "boolean"
		},
		"highlightTokenPairs": {
			"type": "object"
		},
		"keywordList": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"braceTokenPairs": {
			"type": "object"
		}
	}
}

=== dandoh/intellij-dtlc/lang/agda.json
{
	"languageName": "Agda",
	"constantPrefix": "AGDA",
	"exeName": "agda",
	"runConfigInit": "",
	"trimVersion": "version.substring(\"Agda version\".length()).trim()",
	"supportsParsing": true,
	"highlightTokenPairs": {
		"KEYWORD": "KEYWORD",
		"IDENTIFIER": "IDENTIFIER",
		"COMMA": "COMMA",
		"PAREN": "PARENTHESES",
		"BRACE": "BRACES",
		"BRACK": "BRACKETS",
		"SEMICOLON": "SEMICOLON",
		"LINE_COMMENT": "LINE_COMMENT",
		"BLOCK_COMMENT": "BLOCK_COMMENT",
		"FUNCTION_NAME": "FUNCTION_DECLARATION",
		"DOT": "DOT",
		"NUMBER": "NUMBER",
		"STR_LIT": "STRING",
		"CHR_LIT": "STRING",
		"FLOAT": "NUMBER",
		"ARROW": "OPERATION_SIGN",
		"HOLE": "LABEL",
		"PRAGMA": "METADATA"
	}
}

=== dandoh/intellij-dtlc/lang/cubicaltt.json
{
	"languageName": "CubicalTT",
	"constantPrefix": "CUBICAL_TT",
	"exeName": "cubical",
	"runConfigInit": "",
	"trimVersion": "version.trim()",
	"supportsParsing": true,
	"highlightTokenPairs": {
		"KEYWORD": "KEYWORD",
		"IDENTIFIER": "IDENTIFIER",
		"COMMA": "COMMA",
		"PAREN": "PARENTHESES",
		"BRACK": "BRACKETS",
		"SEMICOLON": "SEMICOLON",
		"LINE_COMMENT": "LINE_COMMENT",
		"BLOCK_COMMENT": "BLOCK_COMMENT",
		"FUNCTION_NAME": "FUNCTION_DECLARATION",
		"DATATYPE_NAME": "CLASS_NAME",
		"UNDEFINED": "KEYWORD",
		"HOLE": "LABEL",
		"DIMENSION": "NUMBER",
		"PROJECTION": "INSTANCE_FIELD"
	},
	"keywordList": [
		"transparentAll",
		"transparent",
		"transport",
		"undefined",
		"import",
		"module",
		"mutual",
		"opaque",
		"split@",
		"unglue",
		"hComp",
		"hdata",
		"PathP",
		"split",
		"where",
		"comp",
		"data",
		"fill",
		"glue",
		"Glue",
		"with",
		"id",
		"id",
		"let",
		"Id",
		"in"
	]
}

=== dandoh/intellij-dtlc/lang/mlang.json
{
	"languageName": "Mlang",
	"constantPrefix": "M_LANG",
	"exeName": "mlang.jar",
	"generateCliState": false,
	"supportsParsing": true,
	"highlightTokenPairs": {
		"KEYWORD": "KEYWORD",
		"IDENTIFIER": "IDENTIFIER",
		"COMMA": "COMMA",
		"PAREN": "PARENTHESES",
		"BRACE": "BRACES",
		"BRACK": "BRACKETS",
		"LINE_COMMENT": "LINE_COMMENT",
		"BLOCK_COMMENT": "BLOCK_COMMENT",
		"FUNCTION_NAME": "FUNCTION_DECLARATION",
		"DIMENSION": "NUMBER"
	}
}

=== dandoh/intellij-dtlc/lang/yacctt.json
{
	"languageName": "YaccTT",
	"constantPrefix": "YACC_TT",
	"exeName": "yacctt",
	"runConfigInit": "",
	"trimVersion": "version.trim()",
	"supportsParsing": true,
	"highlightTokenPairs": {
		"KEYWORD": "KEYWORD",
		"IDENTIFIER": "IDENTIFIER",
		"COMMA": "COMMA",
		"PAREN": "PARENTHESES",
		"BRACK": "BRACKETS",
		"SEMICOLON": "SEMICOLON",
		"LINE_COMMENT": "LINE_COMMENT",
		"BLOCK_COMMENT": "BLOCK_COMMENT",
		"FUNCTION_NAME": "FUNCTION_DECLARATION",
		"DATATYPE_NAME": "CLASS_NAME",
		"UNDEFINED": "KEYWORD",
		"HOLE": "LABEL",
		"DIMENSION": "NUMBER",
		"PROJECTION": "INSTANCE_FIELD"
	}
}
